The Sinch Conversation API allows you to send and receive messages globally over SMS, RCS, WhatsApp, Viber Business, Facebook Messenger and other popular channels. The Conversation API endpoint uses built-in transcoding gives you the power of conversation across all supported channels and, if required, full control over channel specific features. Additionally, a single callback contains all aspects of the conversation for easy integration into the Sinch portfolio of services or any third-party platform. Conversation API is available globally with hosting locations in the US - East and the EU - Ireland, and additional channels will be supported as they become popular.

Conversation API offers one single API endpoint for sending and receiving messages across the most popular channels (SMS, RCS, WhatsApp, Viber Business, Facebook messenger and more) using one unified format. For more advanced messaging use cases, it offers conversations, contacts, switching between Bot and Human chats, and much more.

Conversation API Overview

Different message channel (bearer) features and functions are supported through built-in transcoding. As a developer, you have the option to use either a global message template and for it to be automatically transcoded to each message channel format, or simply ignore transcoding and specify an exact layout for the channel you are interested in.

The benefits of this approach are that a developer needs to only become familiar with one Messaging API and yet have the power of conversations across all supported channels, still offering full control over channel specific features if required.

Further, it does not matter which conversation channel the customer engages over, or switch between a single callback contains all aspects of the conversation for easy integration into the Sinch portfolio of services, or any third-party platform.