Sinch has released a package of nodes for Node-RED, which integrates with Sinch Conversation API and enables you to send and receive messages on most popular messaging services around the world. Currently supported channels are:

    SMS
    MMS
    RCS
    WhatsApp
    Facebook Messenger
    Instagram
    WeChat
    KakaoTalk
    Line
    Telegram
    Viber Bot
    Viber Business Messages. 

Node-RED is a flow-based, low-code development tool for visual programming for wiring together hardware devices, APIs and online services. It provides a web browser-based editor that makes it easy to wire together flows using the wide range of nodes in the palette that can be deployed to its runtime in a single-click. 

 

 
 

There are numerous use-cases for sending and receiving messages which depend on your particular needs, for example, Chatbots, Campaigns or auto-responses. All of these use-cases can be easily implemented using only the Sinch Messaging nodes in Node-RED. They can also be seamlessly used together with any of the native nodes provided by Node-RED.  

 

The Sinch Messaging nodes consists of six nodes: 

 
Start Conversation node : Used to configure the channel and number/identity for the recipient of an outgoing message. Also used to set variables which will be stored in the Conversation API and available throughout the flow.
Received Message node : Used to receive inbound messages from Sinch Conversation API for a specific application.
Send node : Used to send a message or template using the Conversation API.
Message node : Used to configure a Conversation API message. The message is defined in JSON format.
Template node : Used to configure/select a template to send through the Conversation API. Templates are created and edited on the Sinch Dashboard.
Events node : Used to route selected Sinch Conversation API events from the list in the configuration.

 

 To use those nodes, you must have an account with Sinch. To register for a Sinch account, click here.  

 
Installing and Getting Started with the Nodes RED package

Click the following link to learn how to install the Node RED package and get started: Install Node RED and Get Started.  