**Iss 1.1.6**

**Non-conformity procedure**

## References

* [1]

Figure 1: Results of the proposed algorithm.

[MISSING_PAGE_EMPTY:3]

1 Introduction

All deviations from the ISMS governance documentation are non-conformities. Non-conformities and corrective actions are part of the continuous improvement work. Non-conformities must be documented without undue delay upon identification in accordance with this procedure.

DIS is responsible for managing non-conformities in accordance with this procedure. DIS shall compile a summary of non-conformities, corrective actions and results of corrective actions, in the Quality Log (ISMS 1.1.6.1).

## 2 Non-conformity workflow

All non-conformities shall be managed in accordance with this workflow.

All non-conformities must be reported and documented into the Quality Log (4), classified in accordance with the non-conformity classification scheme (3), managed via root cause analysis and corrective action (4.1).

### Handling of non-conformity

To manage a non-conformity, it is required to:

* Determine the cause of the non-conformity,
* Describe (4.1) and execute (4.2) a corrective action, and
* Deal with the consequences of a non-conformity.

[MISSING_PAGE_EMPTY:5]

_Note:_ The actions usually imply the modification or introduction of security controls. Corrective actions should be planned within 30 days.

### 4.2 Execute corrective actions

As part of the execution of a corrective action the following activities have to be performed:

* Implement action(s) to eliminate the cause,
* Verify the effectiveness of corrective action(s),
* Investigate the need for changes of the ISMS and if necessary, perform approved changes on the ISMS.

To deal with the consequence of a corrective action implies that potential incidents are handled according to the incident management policy.

Corrective actions should be executed within 60 days for minor non-conformities and 30 days for major non-conformities.

### 4.3 Documentation of corrective actions

The documentation of corrective actions has to describe:

* The nature of the non-conformity,
* Description of the corrective actions,
* Results and effectiveness of corrective actions.
* Root cause analysis
* Preventative actions
* Continual improvement opportunities or risks